### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by madchicken** [Robbepop/prophet#12]
I don't see any recent activity on this repository, I was wondering if the library is still maintained or not.

**Comment by Robbepop** [comment]
No, it is not maintained. It was one of my first toy Rust projects back when I was still learning the language. If you want to use neural networks there are many other neural networks implemented in Rust that are maintained and have much higher quality.

**Comment by madchicken** [comment]
I was more interested in the prophet algorithm and in his non supervisioned version. Thanks anyway.
